const UserActionTypes = {
 CREATE_USER_START:"CREATE_USER_START",
 CREATE_USER_SUCCESS:"CREATE_USER_SUCCESS",
 CREATE_USER_FAIL:"CREATE_USER_FAIL",

 UPDATE_USER_START:"UPDATE_USER_START",
 UPDATE_USER_SUCCESS:"UPDATE_USER_SUCCESS",
 UPDATE_USER_FAIL:"UPDATE_USER_FAIL",

 GET_USER_START:"GET_USER_START",
 GET_USER_SUCCESS:"GET_USER_SUCCESS",
 GET_USER_FAIL:"GET_USER_FAIL",
}
export default UserActionTypes
