const TicketActionTypes = {
	SET_CUREENT_TICKET_LIST: "SET_CUREENT_TICKET_LIST",
	GET_LIST: "GET_LIST",
	SET_SORT_FLIGHT: "SET_SORT_FLIGHT",
	SET_FILTER_STOPS: "SET_FILTER_STOPS",
	TICKET_START: "SIGN_START",
	TICKET_SUCCESS: "SIGN_SUCCESS",
	TICKET_FAILURE: "SIGN_FAILURE",
}

export default TicketActionTypes
