const dashboardTypes = {
	FETCH_START: "FETCH_START",
	FETCH_DASHBOARD: "FETCH_DASHBOARD",
	SET_DASHBOARD: "SET_DASHBOARD",
	FETCH_DASHBOARD_FAILURE: "FETCH_DASHBOARD_FAILURE",
	PUSH_URL: "PUSH_URL"
}

export default dashboardTypes